import:
  - ~/.config/alacritty/theme.yml
  - ~/.config/alacritty/key_bindings.yml

env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 140
    lines: 36

  position:
    x: 30
    y: 100

  padding:
    x: 0
    y: 0

  dynamic_padding: true
  dynamic_title: false
  decorations: full
  startup_mode: Windowed

font:
  normal:
    family: IBM Plex Mono
    style: Regular

  bold:
    family: IBM Plex Mono
    style: Bold

  italic:
    family: IBM Plex Mono
    style: Italic

  bold_italic:
    family: IBM Plex Mono
    style: Bold Italic

  size: 16

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 2

  use_thin_strokes: true
  builtin_box_drawing: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

cursor:
  style:
    shape: Block
    blinking: Always
  blink_interval: 750
  unfocused_hollow: true
  thickness: 0.15

live_config_reload: true

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true

enable_experimental_conpty_backend: true
