import:
  - ~/.config/alacritty/ayu_dark.yml

env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 0
    lines: 0

  position:
   x: 0
   y: 0

  padding:
    x: 5
    y: 5

  dynamic_padding: true
  decorations: full
  startup_mode: Maximized

font:
  normal:
    family: Iosevka Term
    style: Regular

  bold:
    family: Iosevka Term
    style: Bold

  italic:
    family: Iosevka Term
    style: Italic

  bold_italic:
    family: Iosevka Term
    style: Bold Italic

  size: 18

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 2

  use_thin_strokes: true

background_opacity: 1.0

mouse_bindings:
  - { mouse: Right, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: true

cursor:
  style:
    shape: Block
    blinking: Always
  blink_interval: 750
  unfocused_hollow: true
  thickness: 0.15

live_config_reload: true

enable_experimental_conpty_backend: true

debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false
  ref_test: false

key_bindings:
  # for macos
  - { key: B,   mods: Alt,   chars: "\x1bb" }
  - { key: F,   mods: Alt,   chars: "\x1bf" }
  - { key: W,   mods: Alt,   chars: "\x1bw" }
  - { key: X,   mods: Alt,   chars: "\x1bx" }
