import:
  - ~/.config/alacritty/theme.yml

env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 0
    lines: 0

  position:
    x: 0
    y: 0

  padding:
    x: 0
    y: 0

  dynamic_padding: true
  decorations: full
  startup_mode: Maximized

font:
  normal:
    family: Iosevka Term
    style: Regular

  bold:
    family: Iosevka Term
    style: Bold

  italic:
    family: Iosevka Term
    style: Italic

  bold_italic:
    family: Iosevka Term
    style: Bold Italic

  size: 18

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 2

  use_thin_strokes: true

mouse_bindings:
  - { mouse: Right, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

cursor:
  style:
    shape: Block
    blinking: Always
  blink_interval: 750
  unfocused_hollow: true
  thickness: 0.15

live_config_reload: true

enable_experimental_conpty_backend: true

debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false
  ref_test: false

key_bindings:
  - { key: Return, mods: Alt, action: ToggleFullscreen }

  # use option as meta key on macos
  - { key: Space, mods: Control, chars: "\x00" }
  - { key: B, mods: Command, chars: "\x1bb" }
  - { key: D, mods: Command, chars: "\x1bd" }
  - { key: F, mods: Command, chars: "\x1bf" }
  - { key: G, mods: Command, chars: "\x1bg" }
  - { key: Q, mods: Alt, chars: "\x1bq" }
  - { key: W, mods: Command, chars: "\x1bw" }
  - { key: X, mods: Command, chars: "\x1bx" }
  - { key: Period, mods: Command, chars: "\x1b." }
  - { key: LBracket, mods: Shift|Command, chars: "\x1b{" }
  - { key: RBracket, mods: Shift|Command, chars: "\x1b}" }
