key_bindings:
  - { key: Return, mods: Alt, action: ToggleFullscreen }

  # use option as meta key on macos
  - { key: Space, mods: Control, chars: "\x00" }
  - { key: B, mods: Alt, chars: "\x1bb" }
  - { key: D, mods: Alt, chars: "\x1bd" }
  - { key: F, mods: Alt, chars: "\x1bf" }
  - { key: G, mods: Alt, chars: "\x1bg" }
  - { key: N, mods: Alt, chars: "\x1bn" }
  - { key: P, mods: Alt, chars: "\x1bp" }
  - { key: Q, mods: Alt, chars: "\x1bq" }
  - { key: W, mods: Alt, chars: "\x1bw" }
  - { key: X, mods: Alt, chars: "\x1bx" }
  - { key: Key0, mods: Alt, chars: "\x1b0" }
  - { key: Key1, mods: Alt, chars: "\x1b1" }
  - { key: Key2, mods: Alt, chars: "\x1b2" }
  - { key: Key3, mods: Alt, chars: "\x1b3" }
  - { key: Key4, mods: Alt, chars: "\x1b4" }
  - { key: Key5, mods: Alt, chars: "\x1b5" }
  - { key: Key6, mods: Alt, chars: "\x1b6" }
  - { key: Key7, mods: Alt, chars: "\x1b7" }
  - { key: Key8, mods: Alt, chars: "\x1b8" }
  - { key: Key9, mods: Alt, chars: "\x1b9" }
  - { key: Period, mods: Alt, chars: "\x1b." }
  - { key: LBracket, mods: Shift|Alt, chars: "\x1b{" }
  - { key: RBracket, mods: Shift|Alt, chars: "\x1b}" }
  - { key: Backslash, mods: Shift|Alt, chars: "\x1b|" }
